version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: rsv-system-db
    environment:
      MYSQL_DATABASE: rsvSystemDb
      MYSQL_ROOT_PASSWORD: passw@rd
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db:/tmp/db
    ports:
      - 3319:3306
